### PR TITLE
Fix loading icon

### PR DESCRIPTION
**Pull request by jreidinger**

### CODE REVIEW

**Comment by jreidinger** [comment]
@charlesa can you please review it? thanks related bug report is https://bugzilla.suse.com/show_bug.cgi?id=938530

**Comment by kobliha** [comment]
JFYI, keep in mind that anything in `master` will appear in both TumbleWeed and SLE 12 SP1.

**Comment by jreidinger** [comment]
@kobliha fix is valid for both. Actually change in yast2 discover that yast2-vm use non-existing desktop file for loading icon and new behavior ( which I already relax a bit ) was to raise exception.

**Comment by jreidinger** [comment]
JFYI crash no longer can happen due to https://github.com/yast/yast-yast2/pull/379/files
but fix still helps, as it use vm specific icon instead of yast generic one

**Comment by jreidinger** [comment]
@charlesa ping

**Comment by mvidner** [comment]
Apparently Charles has already applied this fix in a single squashed commit 06c71cd9acdd7424949f68730d96519ca23877c0 . This can therefore be closed.

**Pull request closed without merging**
